### ISSUE TITLE
Relative path for images/attachments

### ISSUE THREAD

**Issue by pmario1** [dullage/flatnotes#142]
On the phone I use another editor (i.e. 1Writer) to maintain my notes. The compatibility is fine except for images. For this app images are only displayed entering the relative path:

`![Kühlschrank](./attachments/IMG_1941.jpeg)`

Is there a setting in flatnotes I have to change or is it something I have to live with? I haven't found any definitons of a markdown standard for declaring the path.

Please keep flatnotes as simple, open and lightweight as it is now.

Thanks for your work and feedback.

**Comment by dullage** [comment]
Hey @pmario1 👋

The trouble is that `./attachments/IMG_1941.jpeg` for flatnotes would translate to something like `/notes/My Note/attachments/IMG_1941.jpeg` as `./` indicates relative to the current path (which would be`/notes/My Note`).

`/attachments/IMG_1941.jpeg` works because `/` indicates relative to the root path. 

So it comes down to what the markdown render considers the root path to be. 

Is the app you're using configured directly to the notes directory or is it maybe configured to a higher directory? For example, if the app points to `documents/notes` then it might be incorrectly looking in `document/attachments`. I hope this makes sense.

**Comment by pmario1** [comment]
Hi,

thanks for your reply. Maybe I should tell you more about my current setup.
I use my NAS to store the notes. I run flatnotes in docker (hosted on proxmox) with a volume bind to to flatnotes root directory on my NAS:
'
...
   volumes:
      - /mnt/nas/flatnotes:/data:rw
...
'
In the app I use a WebDav Connection to access my notes. Starting on the level of the flatnotes root directory as seen above.

Maybe this is the not obvious way to store/access the notes so that's why I run into this rare issue ^^
But  I would like to keep it this way, because it gives me the highest flexibility to access my notes. If there's an easy idea/solution to bring both worlds together I would appreciate it otherwise I have to live with the missing "pictures" in one world.

**Comment by dullage** [comment]
I think this might just be a quirk of 1Writer. I've just tried the same setup and had the same result as you. The path _is_ correct though. `/attachments/my-image.jpg` would resolve to `http://my.webdav.address/attachments/my-image.jpg` which is where the image is.

I can, for example, open my flatnotes folder in VSCode (which has a built-in markdown viewer) and the image URLs work fine:
![image](https://github.com/dullage/flatnotes/assets/16575268/73219ee8-60d8-4c86-824b-6a82c28d5689)

I'm not sure I can help I'm afraid. This is a shame though as [I do like 1Writer](https://adam.dullage.com/posts/flatnotes/).

**Comment by pmario1** [comment]
Thanks for the effort you put in the analysis of my problem. I think I've to get in contact with the 1Writer developer or look for alternative native app. Maybe best would be to use flatnotes for all of my note-taking scenarios...

Important outcome of this conversation is that I know now when using flatnotes I'm not in a cage with my knowledge base and can easily move the other solution if necessary. Whatever reason. Please close the issue

**Comment by lmingzhi** [comment]
Great!  The wikilink(Bidirectional link) is work now!

The following is what I hope to get:

```
- ![it is work 1](../attachments/image_1699597780464_0.png)
- ![it is work 2](/attachments/image_1699597780464_0.png)

- ![I want it work, but now it's not work](../assets/image_1699597780464_0.png)
```

How can I modify the source code?

the `docker-compose.yml` I used is as following:

```yaml
# docker-compose.yml
version: "3"

# https://github.com/Dullage/flatnotes#self-hosted
services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:develop
    environment:
      PUID: 1001
      PGID: 1001
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: "____USERNAME____"
      FLATNOTES_PASSWORD: "____PASSWORD____"
      FLATNOTES_SECRET_KEY: "HHHHaLongRandomSeriesOfCharacters"
    volumes:
      - "./data:/data"
      - "./assets:/data/attachments"
    ports:
      - "38080:8080"
    restart: unless-stopped
```
