### ISSUE TITLE
4.0.4 healthcheck is failing

### ISSUE THREAD

**Issue by mmolitor87** [dullage/flatnotes#181]
In healthcheck.sh you're using the new variable: curl -f http://localhost:${FLATNOTES_PORT}/health || exit 1

If you don't set the variable it uses the docker 'inside' port to query the wrong 'outside' port. In my case 8080 is used by another container. I can obviously resolve this by setting an environment variable but thought you might want to be made aware.

**Comment by mmolitor87** [comment]
Actually, even with the FLATNOTES_PORT set it still fails the healthcheck. http://ipaddress:port/health says "OK".

`docker exec -it flatnotes sh`
`# curl -f http://localhost:${FLATNOTES_PORT}/health || exit 1`
Returns: `"OK"`

`docker ps`
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS                     PORTS                                                                                            NAMES
4cc488aba7c4   dullage/flatnotes:latest               "/entrypoint.sh"         6 minutes ago   Up 5 minutes (unhealthy)   8080/tcp, 0.0.0.0:9080->9080/tcp, :::9080->9080/tcp                                              flatnotes

```
name: flatnotes
services:
    flatnotes:
        container_name: flatnotes
        image: dullage/flatnotes:latest
        environment:
            PUID: 1000
            PGID: 1000
            FLATNOTES_AUTH_TYPE: password
            FLATNOTES_USERNAME: lolusername
            FLATNOTES_PASSWORD: hunter2
            FLATNOTES_SECRET_KEY: hunter2
            FLATNOTES_PORT: 9080
        volumes:
            - /mnt/docker/flatnotes/data:/data
            # Optional. Allows you to save the search index in a different location: 
            # - "./index:/data/.flatnotes"
        ports:
            - 9080:9080
        restart: unless-stopped
```
