### ISSUE TITLE
Totp failure at first login

### ISSUE THREAD

**Issue by ablyes** [dullage/flatnotes#272]
Hello. After a fresh install of Flatnotes (i did 2 fresh installations just in case). I have a 401 error. 
The TOTP code that I enter is correct, the login/password as well. 
I don't know what else should I do. 
I'm under docker  27.4.1

I used this docker compose file : 

```
services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      FLATNOTES_AUTH_TYPE: "totp"
      FLATNOTES_USERNAME: "user"
      FLATNOTES_PASSWORD: "XXXXXX"
      FLATNOTES_SECRET_KEY: "128 digits XXXX"
      FLATNOTES_TOTP_KEY: "30 digit XXXX"
    volumes:
      - "./data:/data"
      # Optional. Allows you to save the search index in a different location: 
      # - "./index:/data/.flatnotes"
    ports:
      - "8444:8080"
    restart: unless-stopped
```
