### ISSUE TITLE
Add Support for Docker Secrets 

### ISSUE THREAD

**Issue by spencerhooks** [dullage/flatnotes#73]
It's very possible this is due to user error, but I'm trying to use docker secrets, and it's not working as expected. I'm following the official docker docs (I think), but Flatnotes is literally using "/var/secrets/username" as the username instead of what is held in the username secret. If I exec into the container and use `cat /var/secrets/username` I can see that the value of the secret is set correctly and is passed successfully into the container.

Here's my compose file:
```yaml
version: "3.1"

services:
  flatnotes:
    image: dullage/flatnotes:latest
    environment:
      PUID: 1000
      GUID: 1000
      FLATNOTES_AUTH_TYPE: password
      FLATNOTES_USERNAME: /run/secrets/username
      FLATNOTES_PASSWORD: password_redacted
      FLATNOTES_SECRET_KEY: key_redacted
    volumes:
      - ./data:/data
    ports:
      - 8087:8080
    secrets:
      - username

secrets:
  username:
    external: true
```

I'm wondering if this is due to the way Flatnotes is using the environment variables (i.e. the use of quotes is causing the app to import the string instead of the value of the secret).

**Comment by dullage** [comment]
Hi @spencerhooks. Personally I haven't used Docker Secrets before so I'm probably not the best person to help. 

From memory, I think Docker Secrets only work when using Docker Swarm. This is what has put me off in the past. Are you using Swarm?

Have you used it successfully with any other containers?

**Comment by dullage** [comment]
Reading further into this it seems that applications have to explicitly build support for Docker Secrets. [This section of the docs](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images) suggests providing alternative `_FILE` environment variables which seems like a good approach. I'm not opposed to making this change so I'll change this issue to an enhancement and will try and get to it when I get a chance.

**Comment by spencerhooks** [comment]
Thanks for looking into it. I tested with a couple of hello_world containers that include environment support and they behaved the same way: treat the environment variable as a string, but still have the secret inside the container at /run/secrets/<name>. So yeah, it seems that unfortunately secret support isn't built in. 

Anyway, given that secrets are tied to swarm and swarm isn't very popular, I won't blame you for making this a pretty low priority 😉 I just wish I could find a simple, but effective way to deal with secrets in docker... The other solutions seem to be meant for large organizations.

**Comment by Mladia** [comment]
docker secrets can be used without a docker swarm as well.

A quick test goes like this:

1) On the host create your secrets file 
``` echo "1234" > /tmp/flatnotes-test-passwd ```

2) Modify docker compose
```
version: "3"

services:
  flatnotes-test:
    container_name: flatnotes-test
    image: dullage/flatnotes:latest
    environment:
      PUID: 1001
      PGID: 1001
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: "user"
      FLATNOTES_PASSWORD: "changeMe!"
      FLATNOTES_SECRET_KEY: "aLongRandomSeriesOfCharacters"
    ports:
      - "8300:8080"
    secrets:
      - flatnotes-test-passwd

secrets:
  flatnotes-test-passwd:
    file: /tmp/flatnotes-test-passwd
```
Start and execute into the container

3) Now the file is accessible inside the container:
```
root@665f5261b05b:/app# cat /run/secrets/flatnotes-test-passwd
1234
```

On start, the server will check if the file with this particular name in /run/secrets exists and if yes, will read the password from there instead of an env variable.
